version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dev_network
  express-app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: express-app
    depends_on:
      - mariadb
    env_file:
      - .env.local
    ports:
      - "3000:3000" # Map the app's port 3000 to the host
    volumes:
      - ./src:/usr/src/app # Bind mount source code for hot-reloading
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    command: npm run dev # Use a development command, such as nodemon
    networks:
      - dev_network



networks:
  dev_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
