FROM node:20

WORKDIR /usr/src/app

ARG DATABASE_URL
ARG NODE_ENV

ENV DATABASE_URL=$DATABASE_URL
ENV NODE_ENV=$NODE_ENV

COPY package*.json  ./
RUN npm install

COPY . .

RUN npm install

RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "dev"]
