FROM node:20

WORKDIR /usr/src/app

ARG DATABASE_URL
ARG NODE_ENV

ENV DATABASE_URL=$DATABASE_URL
ENV NODE_ENV=$NODE_ENV

COPY package*.json  ./

COPY ./src .

COPY ./prisma .

COPY ./tsconfig.json .

COPY ./nodemon.json .

RUN npm install

RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "dev"]
